# Generated by Django 6.0.1 on 2026-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='centro_costo',
            field=models.CharField(default='General', help_text='Ej: Ingeniería, Operaciones, Administrativo', max_length=100, verbose_name='Centro de Costo'),
        ),
    ]
