# Generated by Django 6.0.1 on 2026-01-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_centro_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='unidad_negocio',
            field=models.CharField(choices=[('AUTOMATIZACION', 'Automatización'), ('TELECOMUNICACIONES', 'Telecomunicaciones'), ('ENERGIA', 'Energía')], default='AUTOMATIZACION', max_length=20, verbose_name='Unidad de Negocio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='centro_costo',
            field=models.CharField(default='General', help_text='Ej: AU43388, AGRO10002, AU43399', max_length=100, verbose_name='Centro de Costo'),
        ),
    ]
