# Generated by Django 6.0.1 on 2026-02-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_unidad_negocio_alter_proyecto_centro_costo'),
        ('rrhh', '0002_conocimiento_habilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='requisitos',
            field=models.ManyToManyField(blank=True, to='rrhh.conocimiento', verbose_name='Conocimientos Requeridos'),
        ),
    ]
