# Generated by Django 6.0.1 on 2026-03-05 20:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_cliente_proyecto_cliente'),
        ('rrhh', '0002_conocimiento_habilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='llave_asistencia',
            field=models.CharField(blank=True, help_text='Generada automáticamente. No modificar.', max_length=32, null=True, verbose_name='Llave Secreta TOTP'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Registro')),
                ('tipo_registro', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], default='ENTRADA', max_length=10)),
                ('metodo_validacion', models.CharField(choices=[('QR', 'Escaneo QR'), ('MANUAL', 'Código Numérico')], default='QR', max_length=20, verbose_name='Método de Ingreso')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='proyectos.proyecto')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='rrhh.recurso')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencias',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
