# Generated by Django 6.0.1 on 2026-02-02 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('categoria', models.CharField(blank=True, help_text='Ej: 1. PLCs, 12. Redes', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, '1 - Básico'), (2, '2 - Principiante'), (3, '3 - Intermedio'), (4, '4 - Avanzado'), (5, '5 - Experto')], default=1)),
                ('conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.conocimiento')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='rrhh.recurso')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Matriz de Habilidades',
                'unique_together': {('recurso', 'conocimiento')},
            },
        ),
    ]
